#!/bin/sh
#
# /etc/rc.d/dbus: start/stop dbus messagebus daemon
#

. /etc/rc.subr

PIDFILE=/run/dbus/pid
OPTS="--system"
SOCKET=/run/dbus/system_bus_socket

case $1 in
	start)
		msg "Starting D-BUS Messagebus daemon..."
		mkdir -p /run/dbus
		dbus-uuidgen --ensure
		start_daemon -p $PIDFILE dbus-daemon $OPTS
		;;
	stop)
		msg "Stopping D-BUS Messagebus daemon..."
		stop_daemon -p $PIDFILE dbus-daemon
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		status_daemon dbus-daemon
		;;
	*)
		echo "usage: $0 [start|stop|restart|status]"
		;;
esac

# End of file
