#!/bin/sh
#
# /etc/rc.d/smartd: start/stop smartd
#

. /etc/rc.subr

NAME="smartd"
PROG=/usr/sbin/smartd
PIDFILE=/var/run/$NAME.pid
OPT="-p $PIDFILE"

case $1 in
	start)
		msg "Starting $NAME..."
		start_daemon -p $PIDFILE $PROG $OPT
		;;
	stop)
		msg "Stopping $NAME..."
		stop_daemon $PROG
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		status_daemon $PROG
		;;
	*)
		echo "usage: $0 [start|stop|restart|status]"
		;;
esac

# End of file
