#!/bin/sh
#
# /etc/rc.d/alsa: store/restore ALSA mixer levels
#

. /etc/rc.subr

case $1 in
	start)
		if [ -f /var/lib/alsa/asound.state ]; then
			msg "Restoring ALSA volume state..."
			alsactl restore
		fi
		;;
	stop)
		msg "Saving ALSA volume state..."
		alsactl store
		;;
	restart)
		$0 stop
		sleep 2
		$0 start
		;;
	*)
		echo "Usage: $0 [start|stop|restart]"
		;;
esac

# End of file
